# Generated by Django 3.1.1 on 2020-10-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=2)),
                ('paralelo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=300)),
                ('Explique', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'core_Enfermedad',
                'ordering': ['Tipo'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Edad', models.IntegerField(default=10)),
                ('Email', models.EmailField(default='@gmail.com', max_length=254)),
                ('Sexo', models.CharField(max_length=1)),
                ('Cedula', models.CharField(max_length=200)),
                ('Fecha_Nacimiento', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('N_de_Telefono', models.CharField(max_length=200)),
                ('Codigo_Matricula', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=15)),
                ('user_mod', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'db_table': 'core_estudiante',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Edad', models.IntegerField(default=10)),
                ('Cedula', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('N_de_Telefono', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=15)),
                ('user_mod', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'db_table': 'core_Retiro',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educacion_Formulario', models.CharField(choices=[('A', 'Agregar'), ('SP', 'Solo Padres'), ('PM', 'Mi Padre y Mi Madre'), ('SM', 'Solo Madre'), ('SP', 'Solo Padre'), ('OTRO', 'Otra Persona')], default='A', max_length=100)),
                ('Relacion_Formulario', models.CharField(choices=[('A', 'Agregar'), ('MCD', 'Mayormente Conversan y Deciden en Conjunto'), ('NHC', 'No hay comunicacion'), ('NHC', 'Solo habla lo necesario'), ('CCT', 'Cuando conversan terminan discutiendo')], default='A', max_length=100)),
                ('Conducta_Formulario', models.CharField(choices=[('A', 'Agregar'), ('G', 'Gritan'), ('G', 'Golpean'), ('LQLM', 'Le quitan lo que mas le gusta'), ('LA', 'Le llaman la atencion'), ('NLD', 'No le dicen')], default='A', max_length=100)),
                ('Internet_Formulario', models.CharField(choices=[('A', 'Agregar'), ('G', 'Para Chatiar'), ('G', 'Para Jugar'), ('LQLM', 'Le quitan lo que mas le gusta'), ('LA', 'Para hacer tarea'), ('NLD', 'No uso Internet')], default='A', max_length=100)),
                ('Transporte_Formulario', models.CharField(choices=[('A', 'Agregar'), ('TP', 'Transporte Publico'), ('TP', 'Transporte Privado'), ('TE', 'Transporte Escolar'), ('ST', 'Sin Transporte')], default='A', max_length=100)),
                ('Estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'core_Formulario',
                'ordering': ['Educacion_Formulario'],
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Madre', models.CharField(max_length=200)),
                ('Nombre_Padre', models.CharField(max_length=200)),
                ('Apellido_Padre', models.CharField(max_length=200)),
                ('Apellido_Madre', models.CharField(max_length=200)),
                ('Ocupacion_Padre', models.CharField(max_length=200)),
                ('Ocupacion_Madre', models.CharField(max_length=200)),
                ('Trabaja_Donde_Madre', models.CharField(max_length=200)),
                ('Trabaja_Donde_Padre', models.CharField(max_length=200)),
                ('Estado_Civil_Madre', models.CharField(max_length=200)),
                ('Estado_Civil_Padre', models.CharField(max_length=200)),
                ('Vive_con_el_Niño_Madre', models.CharField(max_length=200)),
                ('Vive_con_el_Niño_Padre', models.CharField(max_length=200)),
                ('Telefonos_Madre', models.CharField(max_length=200)),
                ('Telefonos_Padre', models.CharField(max_length=200)),
                ('Direccion_Madre', models.CharField(max_length=200)),
                ('Direccion_Padre', models.CharField(max_length=200)),
                ('Instruccion_Madre', models.CharField(max_length=200)),
                ('Instruccion_Padre', models.CharField(max_length=200)),
                ('Tutor', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=15)),
                ('user_mod', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'core_Familia',
                'ordering': ['Nombre_Madre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante_Familia_Enfermedad_Formulario_Retiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.enfermedad')),
                ('estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('familia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.familia')),
                ('formulario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.formulario')),
                ('retiro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.retiro')),
            ],
            options={
                'verbose_name': 'Estudiante_Familia_Enfermedad_Formulario_Retiro',
                'verbose_name_plural': 'Estudiantes_Familias_Enfermedades_Formularios_Retiros',
                'db_table': 'core_Es_Fa_En_Fo_Re',
                'ordering': ['estudiante'],
            },
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='Estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante'),
        ),
    ]
